/**
 * WP-04 cost engine tests. Every expected dollar value below was worked
 * out by hand from the published rates (docs/PLAN.md §5: hand-computed,
 * not generated by code), and the per-MTok cases double as a check that
 * `pricing.json` reproduces the pricing page's own table columns.
 */

import { describe, expect, it } from 'vitest'
import { PRICING } from '../config/pricing'
import type { CostBreakdown, RequestRecord, RequestUsage } from './contract'
import {
  addCosts,
  bucketsFromUsage,
  buildUnknownModelReport,
  knownModelIds,
  lookupModel,
  multiplierFor,
  priceRequest,
  priceTokens,
  PricingConfigError,
  sumCosts,
  totalTokens,
  unattributedWriteTokens,
  validatePricingConfig,
  ZERO_COST,
} from './cost'
import type { ModelPricing, PricingConfig } from './pricing'

const CACHE = PRICING.cacheMultipliers
const MTOK = 1_000_000
const STANDARD = { serviceTier: 'standard', speed: 'standard' }

function model(id: string): ModelPricing {
  const m = lookupModel(PRICING, id)
  if (!m) throw new Error(`test needs ${id} in pricing.json`)
  return m
}

function usage(partial: Partial<RequestUsage>): RequestUsage {
  return {
    inputTokens: 0,
    cacheReadInputTokens: 0,
    cacheCreationInputTokens: 0,
    cacheCreation5mTokens: 0,
    cacheCreation1hTokens: 0,
    outputTokens: 0,
    serviceTier: 'standard',
    speed: 'standard',
    ...partial,
  }
}

function request(modelId: string, u: Partial<RequestUsage>): RequestRecord {
  return {
    messageId: `msg_${modelId}`,
    model: modelId,
    timestamp: '2026-08-30T12:00:03.000Z',
    requestStartTimestamp: '2026-08-30T12:00:00.000Z',
    requestStartSource: 'user-ancestor',
    threadId: 'main',
    isSidechain: false,
    usage: usage(u),
  }
}

function expectCost(actual: CostBreakdown, expected: CostBreakdown) {
  for (const key of Object.keys(expected) as (keyof CostBreakdown)[]) {
    expect(actual[key], key).toBeCloseTo(expected[key], 10)
  }
}

const ONE_MTOK_EACH = {
  baseInputTokens: MTOK,
  cacheReadTokens: MTOK,
  cacheWrite5mTokens: MTOK,
  cacheWrite1hTokens: MTOK,
  outputTokens: MTOK,
}

describe('priceTokens reproduces the pricing page table (1 MTok per bucket)', () => {
  // Pricing page columns: base / 5m write / 1h write / cache hit / output.
  it.each([
    ['claude-fable-5', 10, 12.5, 20, 1, 50],
    ['claude-opus-5', 5, 6.25, 10, 0.5, 25],
    ['claude-opus-4-8', 5, 6.25, 10, 0.5, 25],
    ['claude-sonnet-5', 2, 2.5, 4, 0.2, 10],
    ['claude-sonnet-4-6', 3, 3.75, 6, 0.3, 15],
    ['claude-haiku-4-5', 1, 1.25, 2, 0.1, 5],
    ['claude-opus-4-1', 15, 18.75, 30, 1.5, 75],
    ['claude-3-5-haiku-20241022', 0.8, 1, 1.6, 0.08, 4],
  ])('%s', (id, base, w5m, w1h, read, out) => {
    expectCost(priceTokens(ONE_MTOK_EACH, model(id), CACHE, STANDARD), {
      baseInputUsd: base,
      cacheWrite5mUsd: w5m,
      cacheWrite1hUsd: w1h,
      cacheReadUsd: read,
      outputUsd: out,
      totalUsd: base + w5m + w1h + read + out,
    })
  })
})

describe('modifier combinations (hand-computed)', () => {
  it('standard tier, standard speed — Fable 5, 100k tokens per bucket', () => {
    // 0.1 MTok × (10 / 12.50 / 20 / 1 / 50) = 1.00 / 1.25 / 2.00 / 0.10 / 5.00
    const buckets = {
      baseInputTokens: 100_000,
      cacheReadTokens: 100_000,
      cacheWrite5mTokens: 100_000,
      cacheWrite1hTokens: 100_000,
      outputTokens: 100_000,
    }
    expectCost(priceTokens(buckets, model('claude-fable-5'), CACHE, STANDARD), {
      baseInputUsd: 1,
      cacheReadUsd: 0.1,
      cacheWrite5mUsd: 1.25,
      cacheWrite1hUsd: 2,
      outputUsd: 5,
      totalUsd: 9.35,
    })
  })

  it('batch tier halves input and output, caching stacks — Opus 5, 1 MTok each', () => {
    // Batch table: $2.50 in / $12.50 out. Cache: 2.50 × 0.1 = 0.25,
    // 2.50 × 1.25 = 3.125, 2.50 × 2 = 5.
    expectCost(
      priceTokens(ONE_MTOK_EACH, model('claude-opus-5'), CACHE, {
        serviceTier: 'batch',
        speed: 'standard',
      }),
      {
        baseInputUsd: 2.5,
        cacheReadUsd: 0.25,
        cacheWrite5mUsd: 3.125,
        cacheWrite1hUsd: 5,
        outputUsd: 12.5,
        totalUsd: 23.375,
      },
    )
  })

  it('fast mode doubles Opus 5 ($10 / $50), caching stacks on top', () => {
    // 200k base × $10 = 2.00; 300k read × $1 = 0.30; 40k 5m × $12.50 = 0.50;
    // 10k 1h × $20 = 0.20; 100k out × $50 = 5.00 → 8.00
    const buckets = {
      baseInputTokens: 200_000,
      cacheReadTokens: 300_000,
      cacheWrite5mTokens: 40_000,
      cacheWrite1hTokens: 10_000,
      outputTokens: 100_000,
    }
    expectCost(
      priceTokens(buckets, model('claude-opus-5'), CACHE, {
        serviceTier: 'standard',
        speed: 'fast',
      }),
      {
        baseInputUsd: 2,
        cacheReadUsd: 0.3,
        cacheWrite5mUsd: 0.5,
        cacheWrite1hUsd: 0.2,
        outputUsd: 5,
        totalUsd: 8,
      },
    )
  })

  it('fast mode on Opus 4.6 is billed at standard rates (explicit 1)', () => {
    const fast = priceTokens(ONE_MTOK_EACH, model('claude-opus-4-6'), CACHE, {
      serviceTier: 'standard',
      speed: 'fast',
    })
    expectCost(fast, priceTokens(ONE_MTOK_EACH, model('claude-opus-4-6'), CACHE, STANDARD))
    expect(fast.totalUsd).toBeCloseTo(46.75, 10)
  })

  it('batch and fast both applied: 0.5 × 2 = standard (a config-consistency check)', () => {
    const both = priceTokens(ONE_MTOK_EACH, model('claude-opus-5'), CACHE, {
      serviceTier: 'batch',
      speed: 'fast',
    })
    expectCost(both, priceTokens(ONE_MTOK_EACH, model('claude-opus-5'), CACHE, STANDARD))
  })

  it('priority tier is priced at standard rates (capacity commitment, no per-token premium)', () => {
    const priority = priceTokens(ONE_MTOK_EACH, model('claude-fable-5'), CACHE, {
      serviceTier: 'priority',
      speed: 'standard',
    })
    expect(priority.totalUsd).toBeCloseTo(93.5, 10)
  })

  it('unknown tier or speed keys, or absent maps, mean 1.0', () => {
    const bare: ModelPricing = { displayName: 'X', inputPerMTok: 4, outputPerMTok: 8 }
    expect(multiplierFor(undefined, 'anything')).toBe(1)
    expect(multiplierFor({ standard: 1 }, 'turbo')).toBe(1)
    expect(multiplierFor({ standard: 1 }, '__proto__')).toBe(1)
    expect(multiplierFor({ standard: 1 }, 'constructor')).toBe(1)
    const cost = priceTokens(
      {
        baseInputTokens: 500_000,
        cacheReadTokens: 0,
        cacheWrite5mTokens: 0,
        cacheWrite1hTokens: 0,
        outputTokens: 250_000,
      },
      bare,
      CACHE,
      { serviceTier: 'mystery', speed: 'warp' },
    )
    // 0.5 MTok × $4 = 2.00; 0.25 MTok × $8 = 2.00
    expectCost(cost, {
      baseInputUsd: 2,
      cacheReadUsd: 0,
      cacheWrite5mUsd: 0,
      cacheWrite1hUsd: 0,
      outputUsd: 2,
      totalUsd: 4,
    })
  })

  it('zero tokens cost zero', () => {
    const cost = priceTokens(
      {
        baseInputTokens: 0,
        cacheReadTokens: 0,
        cacheWrite5mTokens: 0,
        cacheWrite1hTokens: 0,
        outputTokens: 0,
      },
      model('claude-fable-5'),
      CACHE,
      STANDARD,
    )
    expect(cost).toEqual(ZERO_COST)
  })
})

describe('priceRequest on real-shaped usage (hand-computed)', () => {
  it('the feasibility doc §2 payload on Sonnet 5', () => {
    // input 2 × $2 = 0.000004; read 23472 × $0.20 = 0.0046944;
    // 1h write 13185 × $4 = 0.05274; output 386 × $10 = 0.00386
    const cost = priceRequest(
      request('claude-sonnet-5', {
        inputTokens: 2,
        cacheCreationInputTokens: 13185,
        cacheReadInputTokens: 23472,
        cacheCreation5mTokens: 0,
        cacheCreation1hTokens: 13185,
        outputTokens: 386,
      }),
      PRICING,
    )
    expectCost(cost!, {
      baseInputUsd: 0.000004,
      cacheReadUsd: 0.0046944,
      cacheWrite5mUsd: 0,
      cacheWrite1hUsd: 0.05274,
      outputUsd: 0.00386,
      totalUsd: 0.0612984,
    })
  })

  it("the subagent's first request (F2) on Haiku 4.5 — a 5m write", () => {
    // input 2 × $1 = 0.000002; 5m write 23486 × $1.25 = 0.0293575; output 5 × $5 = 0.000025
    const cost = priceRequest(
      request('claude-haiku-4-5', {
        inputTokens: 2,
        cacheCreationInputTokens: 23486,
        cacheCreation5mTokens: 23486,
        outputTokens: 5,
      }),
      PRICING,
    )
    expectCost(cost!, {
      baseInputUsd: 0.000002,
      cacheReadUsd: 0,
      cacheWrite5mUsd: 0.0293575,
      cacheWrite1hUsd: 0,
      outputUsd: 0.000025,
      totalUsd: 0.0293845,
    })
  })

  it('honors the per-request tier and speed from usage', () => {
    // Opus 5 fast: 1000 base × $10 = 0.01; 100 out × $50 = 0.005
    const cost = priceRequest(
      request('claude-opus-5', { inputTokens: 1000, outputTokens: 100, speed: 'fast' }),
      PRICING,
    )
    expectCost(cost!, {
      baseInputUsd: 0.01,
      cacheReadUsd: 0,
      cacheWrite5mUsd: 0,
      cacheWrite1hUsd: 0,
      outputUsd: 0.005,
      totalUsd: 0.015,
    })
  })

  it('returns null for an unpriced model — never guesses', () => {
    expect(priceRequest(request('claude-mystery-9', { inputTokens: 1 }), PRICING)).toBeNull()
    expect(priceRequest(request('__proto__', { inputTokens: 1 }), PRICING)).toBeNull()
    expect(priceRequest(request('constructor', { inputTokens: 1 }), PRICING)).toBeNull()
    expect(priceRequest(request('toString', { inputTokens: 1 }), PRICING)).toBeNull()
  })
})

describe('unattributed cache writes', () => {
  it('prices writes the split does not cover at the 5m rate', () => {
    // Opus 5: 1000 unattributed × $6.25 = 0.00625
    const u = usage({ cacheCreationInputTokens: 1000 })
    expect(unattributedWriteTokens(u)).toBe(1000)
    expect(bucketsFromUsage(u).cacheWrite5mTokens).toBe(1000)
    expectCost(priceRequest(request('claude-opus-5', u), PRICING)!, {
      baseInputUsd: 0,
      cacheReadUsd: 0,
      cacheWrite5mUsd: 0.00625,
      cacheWrite1hUsd: 0,
      outputUsd: 0,
      totalUsd: 0.00625,
    })
  })

  it('a partial split: residual goes to 5m, the 1h share stays 1h', () => {
    // 400 × $6.25 = 0.0025; 600 × $10 = 0.006
    const u = usage({ cacheCreationInputTokens: 1000, cacheCreation1hTokens: 600 })
    expect(unattributedWriteTokens(u)).toBe(400)
    const cost = priceRequest(request('claude-opus-5', u), PRICING)!
    expect(cost.cacheWrite5mUsd).toBeCloseTo(0.0025, 10)
    expect(cost.cacheWrite1hUsd).toBeCloseTo(0.006, 10)
  })

  it('a fully attributed split has no residual (and never goes negative)', () => {
    expect(
      unattributedWriteTokens(usage({ cacheCreationInputTokens: 100, cacheCreation1hTokens: 100 })),
    ).toBe(0)
    expect(
      unattributedWriteTokens(
        usage({
          cacheCreationInputTokens: 50,
          cacheCreation5mTokens: 30,
          cacheCreation1hTokens: 30,
        }),
      ),
    ).toBe(0)
  })
})

describe('aggregation helpers', () => {
  it('totalTokens follows the suppression-policy definition (input + read + write + output)', () => {
    expect(
      totalTokens(
        usage({
          inputTokens: 2,
          cacheReadInputTokens: 1000,
          cacheCreationInputTokens: 100,
          cacheCreation1hTokens: 100,
          outputTokens: 50,
        }),
      ),
    ).toBe(1152)
  })

  it('addCosts / sumCosts add every line and the total', () => {
    const a: CostBreakdown = {
      baseInputUsd: 1,
      cacheReadUsd: 2,
      cacheWrite5mUsd: 3,
      cacheWrite1hUsd: 4,
      outputUsd: 5,
      totalUsd: 15,
    }
    const b: CostBreakdown = {
      baseInputUsd: 0.5,
      cacheReadUsd: 0.5,
      cacheWrite5mUsd: 0.5,
      cacheWrite1hUsd: 0.5,
      outputUsd: 0.5,
      totalUsd: 2.5,
    }
    expect(addCosts(a, b)).toEqual({
      baseInputUsd: 1.5,
      cacheReadUsd: 2.5,
      cacheWrite5mUsd: 3.5,
      cacheWrite1hUsd: 4.5,
      outputUsd: 5.5,
      totalUsd: 17.5,
    })
    expect(sumCosts([a, b, a])).toEqual({
      baseInputUsd: 2.5,
      cacheReadUsd: 4.5,
      cacheWrite5mUsd: 6.5,
      cacheWrite1hUsd: 8.5,
      outputUsd: 10.5,
      totalUsd: 32.5,
    })
    expect(sumCosts([])).toEqual(ZERO_COST)
  })

  it('buildUnknownModelReport aggregates excluded requests and tokens, distinct models in order', () => {
    const report = buildUnknownModelReport(
      [
        request('claude-opus-5', { inputTokens: 10 }),
        request('claude-mystery-9', { inputTokens: 100, outputTokens: 50 }),
        request('claude-other-1', { cacheReadInputTokens: 1000 }),
        request('claude-mystery-9', { cacheCreationInputTokens: 7 }),
      ],
      PRICING,
    )
    expect(report).toEqual({
      models: ['claude-mystery-9', 'claude-other-1'],
      excludedRequests: 3,
      excludedTotalTokens: 1157,
    })
  })

  it('knownModelIds lists the config keys', () => {
    const ids = knownModelIds(PRICING)
    expect(ids.has('claude-opus-5')).toBe(true)
    expect(ids.has('claude-mystery-9')).toBe(false)
  })
})

describe('shipped pricing.json', () => {
  it('validates and covers the model ids observed in real Claude Code logs', () => {
    expect(() => validatePricingConfig(PRICING)).not.toThrow()
    for (const id of [
      'claude-opus-5',
      'claude-opus-4-8',
      'claude-fable-5',
      'claude-sonnet-5',
      'claude-haiku-4-5',
    ]) {
      expect(lookupModel(PRICING, id), id).toBeDefined()
    }
    expect(PRICING.cacheMultipliers).toEqual({ read: 0.1, write5m: 1.25, write1h: 2 })
    expect(PRICING.source).toBe('https://platform.claude.com/docs/en/about-claude/pricing')
    expect(PRICING.pricesAsOf).toMatch(/^\d{4}-\d{2}-\d{2}$/)
  })

  it('never marks a fast-mode premium on a model the page does not list for it', () => {
    for (const [id, m] of Object.entries(PRICING.models)) {
      const fast = multiplierFor(m.speedMultipliers, 'fast')
      if (id === 'claude-opus-5' || id === 'claude-opus-4-8') expect(fast, id).toBe(2)
      else expect(fast, id).toBe(1)
    }
  })

  it('every model has batch = 0.5 and standard = 1', () => {
    for (const [id, m] of Object.entries(PRICING.models)) {
      expect(multiplierFor(m.serviceTierMultipliers, 'batch'), id).toBe(0.5)
      expect(multiplierFor(m.serviceTierMultipliers, 'standard'), id).toBe(1)
      expect(multiplierFor(m.speedMultipliers, 'standard'), id).toBe(1)
    }
  })
})

describe('validatePricingConfig', () => {
  const valid = (): PricingConfig => JSON.parse(JSON.stringify(PRICING)) as PricingConfig

  it.each<[string, (c: PricingConfig) => unknown]>([
    ['not an object', () => 'nope'],
    ['bad date', (c) => ({ ...c, pricesAsOf: '30/08/2026' })],
    ['non-https source', (c) => ({ ...c, source: 'ftp://x' })],
    ['missing cache multipliers', (c) => ({ ...c, cacheMultipliers: undefined })],
    ['zero cache read', (c) => ({ ...c, cacheMultipliers: { ...c.cacheMultipliers, read: 0 } })],
    ['empty models', (c) => ({ ...c, models: {} })],
    [
      'negative rate',
      (c) => ({ ...c, models: { x: { displayName: 'X', inputPerMTok: -1, outputPerMTok: 1 } } }),
    ],
    [
      'NaN rate',
      (c) => ({
        ...c,
        models: { x: { displayName: 'X', inputPerMTok: Number.NaN, outputPerMTok: 1 } },
      }),
    ],
    [
      'string rate',
      (c) => ({ ...c, models: { x: { displayName: 'X', inputPerMTok: '5', outputPerMTok: 1 } } }),
    ],
    [
      'empty displayName',
      (c) => ({ ...c, models: { x: { displayName: '', inputPerMTok: 1, outputPerMTok: 1 } } }),
    ],
    [
      'standard tier not 1',
      (c) => ({
        ...c,
        models: {
          x: {
            displayName: 'X',
            inputPerMTok: 1,
            outputPerMTok: 1,
            serviceTierMultipliers: { standard: 0.9 },
          },
        },
      }),
    ],
    [
      'standard speed not 1',
      (c) => ({
        ...c,
        models: {
          x: {
            displayName: 'X',
            inputPerMTok: 1,
            outputPerMTok: 1,
            speedMultipliers: { standard: 2 },
          },
        },
      }),
    ],
    [
      'multiplier map is an array',
      (c) => ({
        ...c,
        models: {
          x: { displayName: 'X', inputPerMTok: 1, outputPerMTok: 1, speedMultipliers: [1] },
        },
      }),
    ],
  ])('rejects %s', (_label, mutate) => {
    expect(() => validatePricingConfig(mutate(valid()))).toThrow(PricingConfigError)
  })

  it('accepts a minimal model without multiplier maps', () => {
    const c = valid()
    c.models = { x: { displayName: 'X', inputPerMTok: 1, outputPerMTok: 2 } }
    expect(validatePricingConfig(c)).toBe(c)
  })
})
