/**
 * WP-03 acceptance: parse a ~100MB synthetic session streamed from disk
 * without ever holding the file in one string. The fixture is generated by
 * `scripts/generate-large-fixture.ts` into the git-ignored
 * `fixtures/generated/` on first run and reused afterwards.
 */

import { createReadStream } from 'node:fs'
import { Readable } from 'node:stream'
import { describe, expect, it } from 'vitest'
import {
  ensureLargeFixture,
  LARGE_FIXTURE_PATH,
  LARGE_FIXTURE_TARGET_BYTES,
} from '../../scripts/generate-large-fixture.ts'
import { MAX_LINE_LENGTH_BYTES, type EngineProgress } from './contract'
import { JsonlLineSplitter } from './jsonl-stream'
import { MAIN_THREAD_ID, parseSession } from './parser'

const CHUNK_BYTES = 256 * 1024

describe('parseSession on a 100MB synthetic file', () => {
  it('streams it in bounded memory and gets every count right', async () => {
    const manifest = ensureLargeFixture()
    expect(manifest.bytes).toBeGreaterThanOrEqual(LARGE_FIXTURE_TARGET_BYTES)

    const splitter = new JsonlLineSplitter()
    const progress: EngineProgress[] = []
    const stream = Readable.toWeb(
      createReadStream(LARGE_FIXTURE_PATH, { highWaterMark: CHUNK_BYTES }),
    ) as ReadableStream<Uint8Array>

    const parsed = await parseSession(stream, {
      fileName: 'large-session.jsonl',
      fileSizeBytes: manifest.bytes,
      splitter,
      onProgress: (p) => progress.push(p),
    })

    // Memory: the splitter only ever buffers one partial line plus the
    // chunk that completes it — nowhere near the file or even the cap.
    expect(splitter.peakPendingBytes).toBeLessThan(MAX_LINE_LENGTH_BYTES)
    expect(splitter.peakPendingBytes).toBeLessThan(CHUNK_BYTES)

    expect(parsed.stats).toEqual({
      totalLines: manifest.totalLines,
      nonEmptyLines: manifest.totalLines,
      malformedLines: 0,
      skippedRecordTypes: manifest.skippedRecordTypes,
      assistantRows: manifest.assistantRows,
      dedupedRequests: manifest.requests,
      syntheticRowsExcluded: 0,
      invalidUsageRowsSkipped: 0,
    })
    expect(parsed.requests).toHaveLength(manifest.requests)
    // The fixture's skipped rows are all classified bookkeeping types, so they
    // are counted in the stats above without raising a warning.
    expect(parsed.verdict).toBe('valid')
    expect(parsed.warnings).toEqual([])
    expect(parsed.metadata.title).toBe(manifest.lastTitle)
    expect(parsed.metadata.models).toEqual(['claude-fable-5'])
    expect(parsed.metadata.fileSizeBytes).toBe(manifest.bytes)

    // Every request resolved its start from a user ancestor, in order.
    expect(parsed.requests.every((r) => r.requestStartSource === 'user-ancestor')).toBe(true)
    expect(parsed.requests.every((r) => r.threadId === MAIN_THREAD_ID)).toBe(true)
    expect(parsed.requests[0].messageId).toBe('msg_large_0')
    expect(parsed.requests.at(-1)?.messageId).toBe(`msg_large_${manifest.requests - 1}`)

    // Progress: monotonic, roughly once per MB, ending at the exact size.
    expect(progress.length).toBeGreaterThan(50)
    for (let i = 1; i < progress.length; i++) {
      expect(progress[i].bytesProcessed).toBeGreaterThanOrEqual(progress[i - 1].bytesProcessed)
    }
    expect(progress.at(-1)).toEqual({
      phase: 'parsing',
      bytesProcessed: manifest.bytes,
      totalBytes: manifest.bytes,
      requestsSeen: manifest.requests,
    })
  }, 120_000)
})
