/**
 * WP-06 — publish the scenario captures as the app's bundled samples.
 *
 * Copies every `fixtures/captured/scenarios/<name>/session.jsonl` to
 * `public/samples/<name>.jsonl` and writes `public/samples/index.json`, the
 * list the sample loader (WP-07) reads. Titles and descriptions come from
 * each capture's `capture.json`; the expected verdict comes from the
 * capture's golden, so the index can never disagree with the engine.
 *
 * Run: `node scripts/sync-samples.ts`. `src/engine/golden.test.ts` asserts
 * the copies are byte-identical to their fixtures and the index is current.
 */

import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  writeFileSync,
} from 'node:fs'
import { join } from 'node:path'

export const SCENARIOS_DIR = join('fixtures', 'captured', 'scenarios')
export const SAMPLES_DIR = join('public', 'samples')
export const SAMPLES_INDEX = join(SAMPLES_DIR, 'index.json')

export interface SampleEntry {
  /** File name under public/samples/. */
  file: string
  title: string
  description: string
  /** The fixture this sample is a copy of, relative to the repo root. */
  source: string
  claudeCodeVersions: string[]
  /** Main-bucket verdict from the golden, so the UI can promise what the sample shows. */
  expectedRecommendation: string
  observedTtl: string | null
  requestCount: number
}

export interface SamplesIndex {
  $comment: string
  samples: SampleEntry[]
}

interface CaptureJson {
  title: string
  description: string
  source: { claudeCodeVersions: string[] }
}

interface Golden {
  outcome: string
  buckets?: {
    bucket: string
    recommendation: string
    observedTtl: string | null
    requestCount: number
  }[]
}

export function buildSamplesIndex(): SamplesIndex {
  const samples: SampleEntry[] = []
  if (!existsSync(SCENARIOS_DIR)) return { $comment: comment(), samples }
  for (const name of readdirSync(SCENARIOS_DIR).sort()) {
    const dir = join(SCENARIOS_DIR, name)
    const session = join(dir, 'session.jsonl')
    if (!existsSync(session)) continue
    const capture = JSON.parse(readFileSync(join(dir, 'capture.json'), 'utf8')) as CaptureJson
    const goldenPath = join('fixtures', 'golden', `captured__scenarios__${name}__session.json`)
    const golden = JSON.parse(readFileSync(goldenPath, 'utf8')) as Golden
    const main = golden.buckets?.find((b) => b.bucket === 'main')
    if (golden.outcome !== 'analysis' || !main) {
      throw new Error(
        `${name}: a bundled sample must analyze cleanly (golden says ${golden.outcome})`,
      )
    }
    samples.push({
      file: `${name}.jsonl`,
      title: capture.title,
      description: capture.description,
      source: session.replaceAll('\\', '/'),
      claudeCodeVersions: capture.source.claudeCodeVersions,
      expectedRecommendation: main.recommendation,
      observedTtl: main.observedTtl,
      requestCount: main.requestCount,
    })
  }
  return { $comment: comment(), samples }
}

function comment(): string {
  return 'Generated by scripts/sync-samples.ts from fixtures/captured/scenarios/ — do not edit by hand.'
}

export function renderIndex(index: SamplesIndex): string {
  return JSON.stringify(index, null, 2) + '\n'
}

function main(): void {
  mkdirSync(SAMPLES_DIR, { recursive: true })
  const index = buildSamplesIndex()
  for (const sample of index.samples) {
    copyFileSync(sample.source, join(SAMPLES_DIR, sample.file))
    console.log(`copied ${sample.source} -> ${join(SAMPLES_DIR, sample.file)}`)
  }
  writeFileSync(SAMPLES_INDEX, renderIndex(index))
  console.log(`wrote ${SAMPLES_INDEX} (${index.samples.length} samples)`)
}

// Only run when executed directly, so the test can import the helpers.
if (process.argv[1]?.endsWith('sync-samples.ts')) main()
